import { StyleSheet, Text, View, Image, Button } from 'react-native';

const TextCustom = () => {
    return (
        <View style={{
            flex:1,
            backgroundColor: 'white',
            justifyContent: 'flex-start',
            alignItems: 'center',
        }}>
            <Text style={{
                fontSize: 30,
                fontWeight: 'bold',
                marginTop: 20,
            }}>
                GREENCYCLE</Text>
            </View>
    );
}
export default TextCustom;
            